
position_controllers:
    joint_01: {Kp: 16, Ki: 0, Kd: 0.4}
    joint_02: {Kp: 12, Ki: 0, Kd: 0.2}
    joint_03: {Kp: 8, Ki: 0, Kd: 0.2}
    prismatic: {Kp: 25, Ki: 0, Kd: 10}
    # joint_01_2: {Kp: 28, Ki: 0.5, Kd: 1}
    # joint_02_2: {Kp: 20, Ki: 0.4, Kd: 0.6}
    # joint_03_2: {Kp: 12, Ki: 0.3, Kd: 0.7}
# step size for pid controllers
ts: 0.01
