// Generated by gencpp from file mrm_training_force/Floatarray.msg
// DO NOT EDIT!


#ifndef MRM_TRAINING_FORCE_MESSAGE_FLOATARRAY_H
#define MRM_TRAINING_FORCE_MESSAGE_FLOATARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mrm_training_force
{
template <class ContainerAllocator>
struct Floatarray_
{
  typedef Floatarray_<ContainerAllocator> Type;

  Floatarray_()
    : data()  {
    }
  Floatarray_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::mrm_training_force::Floatarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mrm_training_force::Floatarray_<ContainerAllocator> const> ConstPtr;

}; // struct Floatarray_

typedef ::mrm_training_force::Floatarray_<std::allocator<void> > Floatarray;

typedef boost::shared_ptr< ::mrm_training_force::Floatarray > FloatarrayPtr;
typedef boost::shared_ptr< ::mrm_training_force::Floatarray const> FloatarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mrm_training_force::Floatarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mrm_training_force::Floatarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mrm_training_force

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mrm_training_force': ['/home/joshua/robot_ws_earlier/src/mrm_training_force/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mrm_training_force::Floatarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mrm_training_force::Floatarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrm_training_force::Floatarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mrm_training_force::Floatarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrm_training_force::Floatarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mrm_training_force::Floatarray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mrm_training_force::Floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "788898178a3da2c3718461eecda8f714";
  }

  static const char* value(const ::mrm_training_force::Floatarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x788898178a3da2c3ULL;
  static const uint64_t static_value2 = 0x718461eecda8f714ULL;
};

template<class ContainerAllocator>
struct DataType< ::mrm_training_force::Floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mrm_training_force/Floatarray";
  }

  static const char* value(const ::mrm_training_force::Floatarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mrm_training_force::Floatarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] data\n\
";
  }

  static const char* value(const ::mrm_training_force::Floatarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mrm_training_force::Floatarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Floatarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mrm_training_force::Floatarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mrm_training_force::Floatarray_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MRM_TRAINING_FORCE_MESSAGE_FLOATARRAY_H
