
collision_reward: -2000.0 # reward
reach_lim_reward: -1000.0 # reward

# weight_r1: 500.0 # Weight for distance from desired point (Huber loss)
weight_r1: 1.5 # Weight for distance from desired point (Ln loss)

weight_r2: 0.0 # high penalty on joint efforts so that a more natural movement can be generated
weight_r3: 0.3 # initial weight for distance from obstacles


max_update_rate: 2000
running_step: 0.1   # in seconds, simulation time

# joint limits parameters
prismatic_lim: [-0.01, 0.4]
joint_01_lim: [-3, 3]
joint_02_lim: [-3, 3]
joint_03_lim: [-3, 3]
